import type { RegistrationField } from "@/lib/types";

export const DEFAULT_REGISTRATION_FIELDS: Omit<RegistrationField, "id">[] = [
  {
    key: "first_name",
    label: "Nome",
    field_type: "text",
    required: true,
    active: true,
    sort_order: 1,
    options: [],
  },
  {
    key: "last_name",
    label: "Cognome",
    field_type: "text",
    required: true,
    active: true,
    sort_order: 2,
    options: [],
  },
  {
    key: "phone",
    label: "Telefono",
    field_type: "tel",
    required: true,
    active: true,
    sort_order: 3,
    options: [],
  },
  {
    key: "email",
    label: "Email",
    field_type: "email",
    required: true,
    active: true,
    sort_order: 4,
    options: [],
  },
  {
    key: "children_under_3",
    label: "N. Bambini <3 anni",
    field_type: "number",
    required: true,
    active: true,
    sort_order: 5,
    options: [],
  },
  {
    key: "children_over_3_labs",
    label: "N. Bambini >3 nei laboratori",
    field_type: "number",
    required: true,
    active: true,
    sort_order: 6,
    options: [],
  },
  {
    key: "adults",
    label: "N. Adulti",
    field_type: "number",
    required: true,
    active: true,
    sort_order: 7,
    options: [],
  },
  {
    key: "country",
    label: "Paese di provenienza",
    field_type: "text",
    required: true,
    active: true,
    sort_order: 8,
    options: [],
  },
];
